### ISSUE TITLE
Add support for doT.js

### ISSUE THREAD

**Issue by AsyncBanana** [fastify/point-of-view#161]
## 🚀 Feature Proposal

Add support for the template engine [doT.js](https://github.com/olado/doT)

## Motivation

doT.js is a fast growing template engine and would work well with Fastify, because one of it's main advantages is performance

## Example
People would be able to use doT.js as they would any supported template engine:
`engine: {
    doT: require('dot')
}`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by alemagio** [comment]
Hi
I would work on this if no one else is already doing it.

**Comment by mcollina** [comment]
go for it!

**Comment by alemagio** [comment]
One small concern.

doT has a functionality which is recommended [here](https://github.com/olado/doT#security-considerations) and consists of pre-compiling all the templates to in-memory functions. This can be done just once when the application starts.
The function responsible for this compilation is called `process` and, as explained [here](http://olado.github.io/doT/), it ignores subfolders.

At the moment we allow the user to specify a `root` or `templates` directory in the options or to specify a path when using the `reply.view` decorator like `reply.view('/templates/myTemplate')`.

When the `root` or `teplates` options are specified it is very easy to use the `process` function but if the user wants to specify the path in the `reply.view` decorator we cannot use it because we don't know where the templates are located until we receive a request.

Maybe it is because of my lack of knowledge on doT but I could not find a good way to solve this, so, what do you think if we force the user specify a template directory option in case of doT?

**Comment by mcollina** [comment]
I have no knowledge of dot.js, go for what you think it is best.

**Comment by alemagio** [comment]
I will proceed then unless @AsyncBanana can provide some tips
