### ISSUE TITLE
ASK, how to exclude minify for spesific routes?

### ISSUE THREAD

**Issue by aalfiann** [fastify/point-of-view#200]
This is not an issue, I just don't know how to exclude minifier for spesific routes?
Is this possible? how?

Thank you.

**Comment by mcollina** [comment]
I don't think it's possible.

**Comment by aalfiann** [comment]
I hope there is a feature for this.

Right now I just modify to spesific routes directly.

Not hard but seems not clean to my routes.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Adibla** [comment]
I could watch this issue if no one else intends to. I have just an advice to ask you: Is there a way to obtain current path from fastify object in order to access it from getTemplate function? Otherwise I could pass it to the function from the caller together with callback and file, What do you think? Thanks

**Comment by mcollina** [comment]
req.context.url should have the route definition (console.log req.context to be sure). req.url have the current path.

**Comment by Adibla** [comment]
thank you very much, then I will pass the context of the request to the function from the caller. I'll do a MR to confirm soon
